### ISSUE TITLE
Compiling Help

### ISSUE THREAD

**Issue by AM7999** [AidanLatno/LATNO_ENGINE#2]
Hi, I was running into some issues compiling Latno Engine in Visual Studio 2022, on compiling with the options "Release, x64, Local Windows Debugger" i recive an error output from the terminal (will embed file) 

[error.txt](https://github.com/AidanLatno/LATNO_ENGINE/files/13059521/error.txt)

**Comment by AidanLatno** [comment]
Hi! Those errors are just due to some simple reworking we were doing on the engine. The changes have been committed so just pull again and it should work. We are currently working on the documentation inside the code through comments so not all classes have explanations.

Here is a link to the class structure of the engine, you may need to make an account to view it.
https://lucid.app/lucidchart/07e42454-b605-4edd-b75a-b012d3d9ac23/edit?viewport_loc=26%2C-2508%2C2580%2C1330%2C0_0&invitationId=inv_3bb5fb15-9527-4efc-a4d3-db6a5f41db56<https://lucid.app/lucidchart/07e42454-b605-4edd-b75a-b012d3d9ac23/edit?viewport_loc=26%2C-2508%2C2580%2C1330%2C0_0&invitationId=inv_3bb5fb15-9527-4efc-a4d3-db6a5f41db56T>

Thanks for reaching out!
________________________________
From: AM7999 ***@***.***>
Sent: Friday, October 20, 2023 6:28 PM
To: AidanLatno/LATNO_ENGINE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AidanLatno/LATNO_ENGINE] Compiling Help (Issue #2)


Hi, I was running into some issues compiling Latno Engine in Visual Studio 2022, on compiling with the options "Release, x64, Local Windows Debugger" i recive an error output from the terminal (will embed file)

error.txt<https://github.com/AidanLatno/LATNO_ENGINE/files/13059521/error.txt>

**Comment by AM7999** [comment]
Re-opened since i was running into another issue with link.exe, log below.

[error.txt](https://github.com/AidanLatno/LATNO_ENGINE/files/13059787/error.txt)

**Comment by AidanLatno** [comment]
Check your dependencies folder. This is a common issue we have seen with people first pulling the project. You should have the folders: "GLEW", "GLFW", "glm" and "stb_img".
I've attached zip files of GLEW and GLFW below. If they're missing just decompress them and throw these in the dependencies folder
[GLEW.zip](https://github.com/AidanLatno/LATNO_ENGINE/files/13059801/GLEW.zip)
[GLFW.zip](https://github.com/AidanLatno/LATNO_ENGINE/files/13059802/GLFW.zip)

**Comment by AM7999** [comment]
After inspecting the GitHub repository it doesnt look like GLEW/bin, GLEW/lib seem to be not included, i'll go ahead and add these to my cloned copy and try compiling

**Comment by AM7999** [comment]
After including the files it does seem to compile just fine.
